apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: sdccproject-matching-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "rootpassword"
            - name: DB_HOST
              value: "mysql"
            - name: DB_PORT
              value: "3306"
